### ISSUE TITLE
Quarry block reobtaining

### ISSUE THREAD

**Issue by BiggestBruhMoment** [TelepathicGrunt/TACT#1]
Apparently magnetic quarry block isnt reobtainable after being put into the ground, maybe there could be a config for it to be reobtainable.So it doesnt feel too annoying when player misplace the block as currently if they make that mistake that mean they have to gather resource again to get the block

**Comment by TelepathicGrunt** [comment]
Seems Quarry block is missing the mineable tags

**Comment by TelepathicGrunt** [comment]
https://github.com/AlexModGuy/AlexsCaves/issues/529

**Comment by TelepathicGrunt** [comment]
Fixed in v1.0.3 of TACT by tagging the block properly
