### ISSUE TITLE
[Request] Add support for abyssal chasm

### ISSUE THREAD

**Issue by deadspidervenom** [TelepathicGrunt/TACT#11]
Currently in "tectonic + terralith" (might just be tectonic though) the biome does not generate at all. If "is_cave" does not work, every time i use the locate command it brings me to a deep cold ocean, so something with that might work.

**Comment by TelepathicGrunt** [comment]
I am able to locate command it without issue.
![image](https://github.com/TelepathicGrunt/TACT/assets/40846040/df1358cb-b1b4-4415-bb3c-8c383dd4ffc6)

Teleporting to one coordinate, I see the chasm
![image](https://github.com/TelepathicGrunt/TACT/assets/40846040/42ed3d00-53c3-4abe-8412-36b32f76a88c)

**Comment by deadspidervenom** [comment]
on my end it just takes me to nothing but i also have your mod installed among others.
![image](https://github.com/TelepathicGrunt/TACT/assets/12871122/b4a01891-bfd4-4fe2-a251-0f767549b9d2)

[✔] abridged-forge-1.20.x-1.1.1
  [✔] AdChimneys-1.20.1-10.1.5.1-build.0365
  [✔] AdLods-1.20.1-8.1.1.1-build.0365
  [✔] aether-1.20.1-1.3.1-neoforge
  [✔] Alex's Mobs Music Mod 1.20.1
  [✔] alexscaves-1.1.4
  [✔] alexscavestrimmed-1.0.2
  [✔] alexsdelight-1.5
  [✔] alexsmobs-1.22.8
  [✔] alexsmobsinteraction-2.2
  [✔] amendments-1.20-1.1.18
  [✔] apothitweaks_config
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] Architects-Palette-1.20.1-1.3.6.1
  [✔] architectury-9.2.14-forge
  [✔] astikorcarts-redux-1.20.1-1.1.7
  [✔] athena-forge-1.20.1-3.1.2
  [✔] badpackets-forge-0.4.3
  [✔] balm-forge-1.20.1-7.2.2
  [✔] bbs-1.20.1-0.1.3-forge
  [✔] betterarcheology-1.1.7-1.20.1
  [✔] bobberdetector-0.1.9-1.20.1
  [✔] botarium-forge-1.20.1-2.3.3
  [✔] bwncr-forge-1.20.1-3.17.0
  [✔] castle_in_the_sky-1.20.1-0.6.0
  [✔] caves__canyons-1.2
  [✔] Chimes-v2.0.1-1.20.1
  [✔] Chipped-forge-1.20.1-3.0.4
  [✔] citadel-2.5.4-1.20.1
  [✔] clean_tooltips-1.0-forge-1.20.1
  [✔] cloth-config-11.1.118-forge
  [✔] Clumps-forge-1.20.1-12.0.0.3
  [✔] comforts-forge-6.3.5+1.20.1
  [✔] Controlling-forge-1.20.1-12.0.2
  [✔] Copycats-forge.1.20.1-1.2.6
  [✔] corpse-forge-1.20.1-1.0.12
  [✔] craftingtweaks-forge-1.20.1-18.2.3
  [✔] create_aquatic_ambitions-1.20.1-1.0.0
  [✔] create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.12
  [✔] create_connected-0.7.4-mc1.20.1-all
  [✔] create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.c
  [✔] create_oppenheimered-1.20.1-1.0.2
  [✔] create_power_loader-1.4.0-mc1.20.1
  [✔] create_trimmed
  [✔] create-1.20.1-0.5.1.f
  [✔] create-confectionery1.20.1_v1.1.0
  [✔] Create-Guardian-Beam-Defense-1.3.0b-1.20.1
  [✔] createliquidfuel-2.1.1-1.20.1
  [✔] create-new-age-forge-1.20.1-1.1.2
  [✔] curios-forge-5.8.0-beta.2+1.20.1
  [✔] DeeperCaves-1.20.1-1.2.7
  [✔] domesticationinnovation-1.7.1-1.20.1
  [✔] DripSounds-1.19.4-0.3.2
  [✔] dsbg-1.0-1.20.1
  [✔] dynamic-fps-3.4.2+minecraft-1.20.4-forge
  [✔] easy-piglins-forge-1.20.1-1.0.5
  [✔] easy-villagers-forge-1.20.1-1.1.4
  [✔] emi_loot-0.6.5+1.20.1+forge
  [✔] emi-1.1.4+1.20.1+forge
  [✔] emiffect-forge-1.1.2+mc1.20.1
  [✔] emitrades-forge-1.2.1+mc1.20.1
  [✔] enchantedbookredesign-1.20.1-1
  [✔] ends_delight-1.20.1-1.0.1
  [✔] expandedstorage-10.3.0-beta.4+1.20.1-forge
  [✔] exposure-1.20.1-1.5.1-forge
  [✔] extrasounds-1.2d-1.20.1-forge
  [✔] FancyBlockParticles-1.20.1-forge-1.1.2.0-beta
  [✔] FarmersDelight-1.20.1-1.2.4
  [✔] Fastload-Reforged-mc1.20.1-3.4.0
  [✔] ferritecore-6.0.1-forge
  [✔] findme-3.2.1-forge
  [✔] flower_doubling_1.20.1-1.2.0
  [✔] forge medievalend-1.0.0(1)
  [✔] ForgeEndertech-1.20.1-11.1.3.0-build.0398
  [✔] functionalstorage-1.20.1-1.2.10
  [✔] Galosphere-1.20.1-1.4.1-Forge
  [✔] galospheretrimming-1.20.1-1.0.0
  [✔] geckolib-neoforge-1.20.1-4.4.4
  [✔] GoldenAgeCombat-v8.0.2-1.20.1-Forge
  [✔] gottagofast-1.20.x-lexforge-2.0.1
  [✔] idas_forge-1.9.3+1.20.1
  [✔] ImmediatelyFast-Forge-1.2.11+1.20.4
  [✔] immersive_weathering-1.20.1-2.0.1-forge
  [✔] infinitybuttons-1.20.1-4.0.2
  [✔] integrated_api-1.5.1+1.20.1-forge
  [✔] integrated_stronghold-1.1.1+1.20.1-forge
  [✔] Jade-1.20.1-forge-11.8.0
  [✔] jearchaeology-1.20.1-1.0.3
  [✔] jei-1.20.1-forge-15.3.0.4
  [✔] jess-1.20.1-forge-1.1.0
  [✔] kotlinforforge-4.10.0-all
  [✔] labels-1.20-1.20.1
  [✔] lighty-forge-2.1.2+1.20.1
  [✔] ManyIdeasCore-1.20.1-1.4.2
  [✔] ManyIdeasDoors-1.20.1-1.2.3
  [✔] medieval_buildings-forge-1.0.2(1)
  [✔] memoryleakfix-forge-1.17+-1.1.5
  [✔] mna-forge-1.20.1-3.0.0.11-all
  [✔] modernfix-forge-5.16.0+mc1.20.1
  [✔] modular-routers-12.1.1+mc1.20.1
  [✔] moonlight-1.20-2.11.12-forge
  [✔] MouseTweaks-forge-mc1.20-2.25
  [✔] mutil-1.20.1-6.1.1
  [✔] netherportalfix-forge-1.20-13.0.1
  [✔] nethersdelight-1.20.1-4.0
  [✔] oceansdelight-1.0.2-1.20
  [✔] octolib-1.20.1-0.3
  [✔] Paxi-1.20-Forge-4.0
  [✔] pipe_connector-1.20.1-0.3.4
  [✔] polymorph-forge-0.49.3+1.20.1
  [✔] PuzzlesLib-v8.1.18-1.20.1-Forge
  [✔] Quark-4.0-440
  [✔] raccompat-1.20.1-0.1.1
  [✔] ramcompat-1.20.1-0.1.2.1
  [✔] Rats-1.20.1-8.1.2
  [✔] RecipesLibrary-1.20.1-2.0.1
  [✔] reddens_stone_lanterns_1.0.3-forge1.20.1
  [✔] relics-1.20.1-0.6.4
  [✔] resourcefullib-forge-1.20.1-2.1.24
  [✔] rubidium-mc1.20.1-0.7.1a
  [✔] sculktransporting-1.20.1-1.1.3
  [✔] Searchables-forge-1.20.1-1.0.2
  [✔] SereneSeasons-1.20.1-9.0.0.46
  [✔] Shrink-1.20.1-1.4.5
  [✔] SimpleCopperPipes-1.20.1-1.16
  [✔] sliceanddice-forge-3.2.0
  [✔] smalltetraadditions-5.1
  [✔] sophisticatedbackpacks-1.20.1-3.20.5.1039
  [✔] sophisticatedcore-1.20.1-0.6.18.597
  [✔] sophisticatedstorage-1.20.1-0.10.20.778
  [✔] sound-physics-remastered-forge-1.20.1-1.3.1
  [✔] spawnermod-1.20.1-1.9.3+Forge
  [✘] spawnstructures_forge-1.0.7.jar (disabled)
  [✔] Steam_Rails-1.6.1+forge-mc1.20.1
  [✔] subsurface-1.0
  [✔] supplementaries-1.20-2.8.10
  [✔] tact-1.1.1+1.20.1
  [✔] tectonic-forge-1.19.3-2.3.4
  [✔] Terralith_1.20.4_v2.4.11
  [✔] tetra-1.20.1-6.3.0
  [✔] tetracelium-1.20.1-1.2.0
  [✔] tetraextras-0.1.4-1.20.1
  [✔] tetrasdelight-1.20.1-1
  [✔] the_bumblezone-7.3.4+1.20.1-forge
  [✔] THT-1.20.1-6.1.1
  [✔] TinyCoal-forge-1.20.1-1.1.5
  [✔] titanium-1.20.1-3.8.27
  [✔] ToolBelt-1.20-1.20.0
  [✔] turf-1.20.1-1.0.6
  [✔] UndergroundBunkers-1.0.3-1.19.2-1.20.4-forge
  [✔] VanillaTweaks-forge-1.20.1-1.5.71
  [✔] voicechat-forge-1.20.1-2.5.12
  [✔] world_preview-forge-1.20.1-1.2.2
  [✔] Xaeros_Minimap_24.1.1_Forge_1.20
  [✔] XaerosWorldMap_1.38.4_Forge_1.20
  [✔] YeetusExperimentus-Forge-2.3.0-build.4+mc1.20.1
  [✔] YungsApi-1.20-Forge-4.0.4
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.6
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4
  [✔] Zeta-1.0-16
  [✔] zmedievalmusic-1.20.1-2.1

**Comment by deadspidervenom** [comment]
![image](https://github.com/TelepathicGrunt/TACT/assets/12871122/f13fce1d-b97c-45e8-87aa-83c9b776aa8f)
map view

**Comment by TelepathicGrunt** [comment]
Even with tact on, the same seed and coordinate in my picture in a new world still spawns the abyss
![image](https://github.com/TelepathicGrunt/TACT/assets/40846040/48c17b7d-40cd-45a6-9f32-f0ec1aaac95b)

What I do see is that the biome doesn't always reach the surface but it is spawning. Just farther down underground. This isn't a TACT issue. It's likely an issue with how Alex's Caves interacts with Terralith and Tectonic. The worldgen overhaul mods changes the biome parameters which pushes biomes around and can make some biomes more or less rarer. Alex's Caves's Abyss Chasm is being pushed down and isn't always able to spawn high enough for its terrain shaping to take effect.

You should report this to Alex's Caves's repo since I do not touch the biome spawning code at a all. This si going to require Alex to think of alterative ways of spawning the biome or adjusting the biome's parameters when Terralith/tectonic is present. Another thing you should try is changing the rarity of Abysss Chasm in Alex's Caves configs to see if making it more common helps get it higher.

**Comment by deadspidervenom** [comment]
tectonic makes oceans deeper, they go till deepest -4.

The issue is, its not every spawn of it that does it so checking the same spot on the same seed is not going to showcase the result. It can spawn normally, but tons of people have issue with it spawning along with the other biomes when on alternate terrain gens. However your mod makes the other biomes work flawless for people, but not this biome which from your description the biome is barely touched. Which is why i requested you added support.

Here is some more photos showing you its just not spawning

This one shows the structures spawning in a cold ocean biome, but not the land mass or what not
![image](https://github.com/TelepathicGrunt/TACT/assets/12871122/ec2aa053-3137-405e-a621-9a70bb669dcc)

underneath there is nothing
![image](https://github.com/TelepathicGrunt/TACT/assets/12871122/b0a2c9c9-ac6c-4ed2-b251-0701bc4520b1)

EDIT: there is already a request post in alex's caves about this, however they are sending people to tectonic.

**Comment by TelepathicGrunt** [comment]
Again, this has to do with terralith/tectonic changing how the biome parameters change throughout the world. 

The way the game works is every biome has a set of parameters. And as the world generates, it has some noise generators that generates a slowly changing value for each parameter. The biome whose parameters are closest to a spot’s noise values is the biome that spawns.

Because terralith/tectonic changes how these noise values change values in a way that makes the abyss chasm end up spawning sometimes at only the bottom of the world and not making all the way up to the bottom of the ocean. 

There isn’t anything I can do because the biome parameters of abyss chasm is set by Alex’s Caves directly and incompat in this area is best handled by Alex himself because this will impact his mod with any worldgen overhaul mod that changes the noise generator’s outputs throughout the world

**Comment by deadspidervenom** [comment]
here is the link to the already existing thread for alexs caves
https://github.com/AlexModGuy/AlexsCaves/issues/794#issuecomment-2054110884

**Comment by TelepathicGrunt** [comment]
Closing as I left suggestion on Alex’s Caves repo on the best solution for them to try out. If they can swap noise params, they then can add dedicated support for many more worldgen overhaul mods easily
