### ISSUE TITLE
Tremorzilla griefing configs

### ISSUE THREAD

**Issue by platypushasnohat** [TelepathicGrunt/TACT#14]
While there is an option to disable super destructive tremorzilla beam griefing in Alex's Caves, there is no option to have no griefing. There is also no option to disable tremorzilla griefing blocks it walks into, which gets rather annoying when going up steep hills. Having these configs in TACT would be great.

**Comment by TelepathicGrunt** [comment]
Won’t that make the mob constantly stuck and unable to climb up any hill higher than 2 blocks steps? I assumed the griefing for walking was to let the mob actually move around

**Comment by platypushasnohat** [comment]
Maybe a step height config could be added alongside this?

**Comment by TelepathicGrunt** [comment]
Yep, like I said, they get stuck with the griefing off and have high step height. Their ai is not made to traverse non-flatish terrain. They need to level the area so they can actually walk around with their ai. 

https://github.com/user-attachments/assets/754699d3-b1c6-4050-a405-7c6975773028

**Comment by TelepathicGrunt** [comment]
I'll add the config but any pathfinding issues is something you'll have to live with and do not report the pathfinding issue to Alex's Caves if you turn off the block griefing
