### ISSUE TITLE
[Enhancement] Add a warning about mob spawns for the tag option

### ISSUE THREAD

**Issue by emihead** [TelepathicGrunt/TACT#16]
Hi, I think a warning should be provided for the tag adjustments option. It affects mob spawns in the cave biomes, especially with certain other mods - with the Unusual Fish Mod, a ton of Prawn spawn in cave biomes when this option is on. I think it also affects the Toretoise and Stoneling from Quark
Edit: I think this mod also removes the cave biomes from the has_no_underground_cabins tag? It might be because they're added to is_overworld, but that's probably an Alex issue if it doesn't even check for the has_no_underground_cabins tag if is_overworld is true

**Comment by TelepathicGrunt** [comment]
I do not remove biomes from any tag. 

And adding the biomes to is underground and such tags comes with mod compat such as… spawning other mods mob’s in the caves which is one of the intended purpose. Use In Control mod or look at the offending mod’s config to remove problematic mobs from the biome to finer tune the compat. This is what modpack makers should be doing anyway when creating a modpack by tailoring and configuring mods to work better together.

If the other mods are adding monsters and are overwhelming the primordial cave or Candy cavity biomes, those mob mods are at fault for not respecting this tag: https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/resources/data/forge/tags/worldgen/biome/no_default_monsters.json

make an issue report to those mods to not add monsters to those tagged biomes by default. And use the mod’s configs or In Control mod to remove the problematic mobs from the biomes

**Comment by emihead** [comment]
I wasn't aware of that tag! I'll report that to both of those mods. Thanks for informing me about how things work behind the scenes a bit more.
