### ISSUE TITLE
Plague of Cave Centipedes and Murmurs in Primordial Caves

### ISSUE THREAD

**Issue by Vinzound** [TelepathicGrunt/TACT#3]
There is a bug that causes Cave Centipedes and Murmurs (Alex's Mobs) to be spammed in the Primordial Caves, this bug has been reported in the base Alex's Caves mod and the author comments that the problem comes from TACT. https://github.com/AlexModGuy/AlexsCaves/issues/528

I hope it can be fixed :)

![image](https://github.com/TelepathicGrunt/TACT/assets/144878239/0984f498-d1c0-4b1d-ae2c-0f5d29a5dddc)

**Comment by TelepathicGrunt** [comment]
This is really not a Tact issue. It is an Alex’s Mobs issue as they did not set the weights and rarity of the mobs properly. This will happen with any large modded cave tagged biome 

Generally, the mod that adds the underground mobs would properly cap their mob's rates or use their own mob cap + spawn cost system to space out their mobs in a much better rate. However, I doubt Alex's Mobs will update to adjust their rates/caps/checks. Though you do have a few options of what you can do.

~~First option being to turn off applyTagAdjustments and then take this internal datapack, remove the is_cave tag from it, and apply it to your world like a normal datapack. However, this will impact other mod's behaviors with the cave biomes as the caves won't be tagged as caves anymore. Not ideal.~~
~~https://github.com/TelepathicGrunt/TACT/tree/1.20.1/src/main/resources/datapacks~~

~~Second option being to use the In Control mod to remove certain Alex's Mobs mobs from Alex's Caves caves or adjust their rates. 
https://legacy.curseforge.com/minecraft/mc-mods/in-control~~

~~See if these options helps you out~~

Edit: Alex's Mobs mod has config where you can blacklist the primordial caves for centipedes and murmurs

**Comment by TelepathicGrunt** [comment]
Alex's Mobs has now released a version where their default config will not add monsters to `forge:no_default_monsters` tagged biomes. (You may need to delete their config so it regenerates with this new check)

TACT v1.0.7 adds Primordial Caves to `forge:no_default_monsters` so Alex's Caves will automatically not add monsters to the biome going forward by default if using newly regenerated Alex's Mobs config
