### ISSUE TITLE
Additional compendium config

### ISSUE THREAD

**Issue by Tobias-tech** [TelepathicGrunt/TACT#4]
Hello, this is a copy of a suggestion shared in the official Alex's caves GitHub, I would really like this to be added.
Just wanted to perhaps suggest a new configuration for the cave compendium, to make it not require multiple cave codexs to unlock all the information. For some people (me dumb) it's pretty hard to translate a cave tablet and when achieved, end up using it for the map and search all the information in the wiki instead because it's a quicker alternative, having the option to enable all the entries right away would be pretty comfortable. That's all

**Comment by TelepathicGrunt** [comment]
Linking the Alex's Caves report. 
https://github.com/AlexModGuy/AlexsCaves/issues/639

Doesn't look like it got any activity. I'll look into feasibility of this soon since I got some time free

**Comment by TelepathicGrunt** [comment]
v1.0.6 has the config option now. Set to false by default
