### ISSUE TITLE
Feature Request: Nuke Explosion Size

### ISSUE THREAD

**Issue by OminousDiscovery** [TelepathicGrunt/TACT#5]

**Comment by TelepathicGrunt** [comment]
I suspect the explosion looks and animations are hardcoded to a certain size so this would be a very large effort work just to allow changing size of explosions. You should ask Alex’s Caves instead for the config as they will have the ability to change the size dynamically more easily

**Comment by TelepathicGrunt** [comment]
Closing as invalid as Alex's Caves apparently already has a config option to change size of the nuke:

https://github.com/AlexModGuy/AlexsCaves/commit/87904255bf29e158152d3617f69816b238efca4f#diff-598795f4c493846b40cd74423deca22347d466e64a64644c88c8d35e76133d80
