### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [TelepathicGrunt/TACT#7]
cen you fix epic fight with the Galena Gauntlet
when i use the Galena Gauntlet with epic fight installed the items become inviseable when used the animation dont work and the item dissapear from the inventory longer than normal before the comes back sometimes
log
https://drive.google.com/file/d/1BSTIFBa3R3RppjNx0PdP4Cmxvrqt1v4n/view?usp=sharing

**Comment by TelepathicGrunt** [comment]
Please report this issue to Alex's Caves and Epic Fight mod. This is beyond the scope of what my mod does as what you're describing is more of a full fledge bug that needs to be addressed in either of those two mods. More likely Epic Fight?

**Comment by ShadowSlayerFX1** [comment]
i already did but thanks anyway
