### ISSUE TITLE
Subterranodon stamina config

### ISSUE THREAD

**Issue by platypushasnohat** [TelepathicGrunt/TACT#8]
Subterranodons can be very powerful mounts once outside the primordial caves, and for how easy they are to tame it can feel a bit cheap. A config for the stamina deplete/refresh rate and amount of stamina subterranodons have would be a nice option to have.

**Comment by TelepathicGrunt** [comment]
Just to make sure, was this suggested to Alex’s Cave’s official repo?

**Comment by TelepathicGrunt** [comment]
Linking https://github.com/AlexModGuy/AlexsCaves/issues/804

**Comment by TelepathicGrunt** [comment]
New TACT update out with config to control both recharge and depletion rate of subterranodon's flight meter
