### ISSUE TITLE
Entity Health & Damage Config Values don't carry over into Multiplayer Servers

### ISSUE THREAD

**Issue by xXDasherGamerXx** [TelepathicGrunt/TACT#9]
Setting a new health and/or damage value for any of the entities in the config file don't carry over to a Multiplayer Server, eventually resetting the config file completely after a server restart occurs. The health and damage values do work for Singleplayer Mode however.

**Health/Damage Config taking effect in a Singleplayer World:**
![2024-02-22_14 15 59](https://github.com/TelepathicGrunt/TACT/assets/160932138/0fa9203a-a1f3-4821-aac9-2f41c0aa7b0f)

**Health/Damage Config taking effect in a Multiplayer Server:**
![2024-02-22_14 12 51](https://github.com/TelepathicGrunt/TACT/assets/160932138/de60d4d8-eaef-42cc-be71-5551d29fb3b5)

Minecraft Version: **1.20.1**
Forge Version: **47.2.0**
Alex's Caves Version: **1.1.0**
TACT Version: **1.1.0+1.20.1**
Citadel Version: **2.5.3-1.20.1**

**Here's the modlist:**
[modlist.txt](https://github.com/TelepathicGrunt/TACT/files/14378468/modlist.txt)

**Comment by TelepathicGrunt** [comment]
> eventually resetting the config file completely

That sounds more like the Forge config issue where it can think the config file is invalid and resets it. Make sure that you do not have the config file open in any program when put onto server. That you add or edit the config file while server is off and then close your editing program and then launched server. 

These entity attribute values only apply at game launch. They do not take effect while the game is running and so, editing them while game is running doesn’t make much sense. And trying to edit and save the config file with certain programs like notepad++ will cause forge to reject the file and reset the config file.

**Comment by xXDasherGamerXx** [comment]
> > eventually resetting the config file completely
> 
> That sounds more like the Forge config issue where it can think the config file is invalid and resets it. Make sure that you do not have the config file open in any program when put onto server. That you add or edit the config file while server is off and then close your editing program and then launched server.
> 
> These entity attribute values only apply at game launch. They do not take effect while the game is running and so, editing them while game is running doesn’t make much sense. And trying to edit and save the config file with certain programs like notepad++ will cause forge to reject the file and reset the config file.

It seems to be working now, idk why it was working in the beginning because I didn't use Notepad++ to edit it, and the server was down when I added the edited config file in, wasn't opened in another program or anything

It all seems good now and working fine, my apologies
